# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_ventas.ui'
#
# Created: Mon Aug 31 05:25:55 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 441)
        self.formLayout = QtGui.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboRut = QtGui.QComboBox(Form)
        self.comboRut.setObjectName("comboRut")
        self.comboRut.addItem("")
        self.comboRut.setItemText(0, "")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboRut)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.folio = QtGui.QLineEdit(Form)
        self.folio.setObjectName("folio")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.folio)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.id_prod = QtGui.QComboBox(Form)
        self.id_prod.setObjectName("id_prod")
        self.id_prod.addItem("")
        self.id_prod.setItemText(0, "")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.id_prod)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.precio = QtGui.QLineEdit(Form)
        self.precio.setObjectName("precio")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.precio)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cantidad = QtGui.QLineEdit(Form)
        self.cantidad.setObjectName("cantidad")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cantidad)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_3)
        self.grilla_prod = QtGui.QTableView(Form)
        self.grilla_prod.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.grilla_prod.setAlternatingRowColors(True)
        self.grilla_prod.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.grilla_prod.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.grilla_prod.setSortingEnabled(True)
        self.grilla_prod.setObjectName("grilla_prod")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.grilla_prod)
        self.aceptar = QtGui.QPushButton(Form)
        self.aceptar.setObjectName("aceptar")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.aceptar)
        self.guardar = QtGui.QPushButton(Form)
        self.guardar.setObjectName("guardar")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.guardar)
        self.venta = QtGui.QPushButton(Form)
        self.venta.setObjectName("venta")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.venta)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.comboRut, self.folio)
        Form.setTabOrder(self.folio, self.precio)
        Form.setTabOrder(self.precio, self.cantidad)
        Form.setTabOrder(self.cantidad, self.grilla_prod)
        Form.setTabOrder(self.grilla_prod, self.aceptar)
        Form.setTabOrder(self.aceptar, self.venta)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Rut Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Folio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "ID Producto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Precio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Detalle Informacion", None, QtGui.QApplication.UnicodeUTF8))
        self.aceptar.setText(QtGui.QApplication.translate("Form", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.guardar.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.venta.setText(QtGui.QApplication.translate("Form", "Terminar Venta", None, QtGui.QApplication.UnicodeUTF8))

